%prod.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost/quarkus_test?reWriteBatchedInserts=true
%prod.quarkus.datasource.username=quarkus_test
%prod.quarkus.datasource.password=quarkus_test
%prod.quarkus.hibernate-orm.schema-management.strategy=create

quarkus.hibernate-orm.jdbc.statement-batch-size=100
quarkus.hibernate-orm.unsupported-properties."hibernate.order_inserts"=true
quarkus.hibernate-orm.unsupported-properties."hibernate.order_updates"=true

# ativar caso queira ver os logs do hibernate
#%dev.quarkus.hibernate-orm.log.sql=true
#%dev.quarkus.hibernate-orm.log.format-sql=true
#%dev.quarkus.log.category."org.hibernate.orm.jdbc.batch".level=TRACE
#%dev.quarkus.log.category."org.hibernate.orm.jdbc.batch".min-level=TRACE

# Tempo limite da transação em segundos (exemplo: 60 segundos)
quarkus.transaction-manager.default-transaction-timeout=120s